#! /bin/bash

# I-ching first setup - BASH
# Last edited: 3 nov 2014
# By kirsten - oknono@github - kirsten@eml.cc

clear

# Ask user to throw three coins
# Coin Toss by pressing enter. 

echo "Thank you for consulting the I Ching, the ancient famous 6-bit fortune telling medium."
echo "We are going to draw six lines, these lines compose a hexagram."
echo "Each line is generated by 3 coin tosses, which your computer will simulate."
echo "Please throw 3 coins, by pressing 'ENTER' 3 times "
echo ""

# Faking the input for now, to see what it looks like on console
# Implement the coin toss and lines later

LINE1="------"
LINE2="--  --"
LINE3="--    "
LINE4="----  "
LINE5="  ----"
LINE6="--  --"
 
# After three tosses, draw line and ask for three more. Repeat until we have 6 lines
# Still faking!
echo "Line one is $LINE1"

echo "Please do the same for line 2"

echo "Line two is $LINE2"

echo "Please do the same for line 3"

echo "Line three is $LINE3"

echo "Please do the same for line 4"

echo "Line four is $LINE4"

echo "Please do the same for line 5"

echo "Line five is $LINE5"

echo "Please do the same for line 6"


echo "Line six is $LINE6"

echo "That are all the actions needed from you"

# Show the hexagram by drawing line 6 on top and line 1 on bottom
echo "Your hexagram is:"
echo "$LINE6"
echo "$LINE5"
echo "$LINE4"
echo "$LINE3"
echo "$LINE2"
echo "$LINE1"


# Show number of Hexagram

echo "This corresponds to Hexagram XX"

# Provide link to text or get text from a website (open source text)

echo "Read more about hexagram here"
